### ISSUE TITLE
Failed update/ Will not power on

### ISSUE THREAD

**Issue by gkuhn427** [Flagtronics/Release#2]
Went to update unit before our race next weekend. Went through update steps, made it to success scrolling.  Froze and shut off. Now will not turn back on or respond at all. Please advise.

**Comment by vtjballeng** [comment]
@gkuhn427, sorry for the delay here. Have you since resolved the problem?

The first step is to make sure you have a reliable power source such as a USB connection or fused vehicle power. 

There is a fail-safe mode that requires following these steps:

1. Disconnect external power (12v or usb)
2. Disconnect the battery
3. Fully hold down both front buttons (you should hear them click)
4. Connect external power (12v or usb) while holding down both front buttons
5. Continue to hold both front buttons until purple scrolling text appears on the ft200. 
6. Release front buttons
7. Go to the [Flagtronics Device Manager](https://github.com/Flagtronics/Release/raw/main/software/ftdevicemanager/current/Flagtronics_Device_Manager_Setup.exe) and you should be able to update it now.
8. Upon reboot you should see status information in the Flagtronics Device Manager software.

**Comment by gkuhn427** [comment]
Yep all good.
